### ISSUE TITLE
Install a cluster visualizer tool to identify traffic patterns

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ocw-asb-spikes#11]
We are trying different traffic visualizer, specifically tracing application to trace our requests throughout the cluster.

Update 05-18-2021:
- On Azure side we are trying Network Watcher along with NSG Flow to determine the flow of traffic
- In k8s cluster, we are trying Jaeger Tracing

Related Resources:
- Traeffic's Tracing Support: https://doc.traefik.io/traefik/observability/tracing/overview/
- Azure Traffic Analysis: https://docs.microsoft.com/en-us/azure/network-watcher/traffic-analytics
- Azure Network Watcher: https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-monitoring-overview

**Comment by gortegaMS** [comment]
Isolated-Traffic Team.

Here are some finding I like to share from my couple hours of work on this issue, hope it helps. 

Visualize network traffic patterns to and from your VMs using open-source tools
https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-using-open-source-tools

Cap Analysis Installation 
https://www.capanalysis.net/ca/how-to-install-capanalysis

At some point I got an error about "Package libssl1.0.0 is not available - version 1.0.0.0"  Package 'libssl1.0.0' has no installation candidate

I solved it by doing this steps

1. - sudo nano /etc/apt/sources.list
2. - add deb http://security.ubuntu.com/ubuntu bionic-security main
3. - sudo apt update && apt-cache policy libssl1.0-dev
4. - sudo apt-get install libssl1.0-dev

I was troubleshooting why Cap Analysis IU page did not work

**Comment by sivamu** [comment]
Looked into Traefik tracing to attain this feature today. Docs to enable tracing at https://doc.traefik.io/traefik/observability/tracing/jaeger/

Steps to use Zipkin as tracer with Traefik

```
# Add following traefik.config TOML
    [tracing]
      [tracing.zipkin]
        httpEndpoint = "http://zipkin.ingress.svc.cluster.local:9411/api/v2/spans"

k create deployment zipkin --image openzipkin/zipkin -n ingress
k expose deployment zipkin --type ClusterIP --port 9411 -n ingress

```

Steps to use Jaeger as tracer with Traefik
```
# Add following traefik.config TOML
    [tracing]
      [tracing.jaeger]
        samplingServerURL = "http://jaeger-collector.ingress.svc.cluster.local:9411/api/v2/spans"
        localAgentHostPort = "jaeger-agent.ingress.svc:6831"
  
# jaeger-operator.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger

helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
helm repo update
helm install jaeger-operator jaegertracing/jaeger-operator -n ingress
kubectl apply -f jaeger-operator.yaml -n ingress

```

**Comment by sivamu** [comment]
Finalized the jaeger deployment by moving the resources to a new namespace and exposing the UI to the public endpoint at
https://basea.aks-sb.com/jaeger/search

**Comment by kev-ms** [comment]
Traffic Analytics using Network Watcher:

- Enable Traffic Watcher in `bartrcloudatx` subscription in the region of NSG (eastus2, centralus)
    https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-create
- Create Storage Account to store Flow Logs
    `az storage account create -n mystorageaccount -g MyResourceGroup -l eastus2 --sku Standard_LRS`
- Enable Flow Logs: 
   In Azure portal, go to Network watcher, and then select NSG flow logs. Select the network security group that you want to 
   enable an NSG flow log for.
    https://docs.microsoft.com/en-us/azure/network-watcher/traffic-analytics#enable-flow-log-settings
- View Traffic Analytics
    https://docs.microsoft.com/en-us/azure/network-watcher/traffic-analytics#view-traffic-analytics
