### ISSUE TITLE
Spike: Install Promitor to scrape Azure Monitor metrics into Prometheus / Grafana dashboard

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ocw-asb-spikes#18]

**Comment by tomkerkhove** [comment]
Happy to help where I can

**Comment by PurpleBriar** [comment]
> Happy to help where I can @PurpleBriar

**Comment by tomkerkhove** [comment]
Nice, thanks for using Promitor! Where can I find the guide? I was looking for it in master but couldn't seem to find it

**Comment by PurpleBriar** [comment]
> Nice, thanks for using Promitor! Where can I find the guide? I was looking for it in master but couldn't seem to find it

I merged it into the spikes/workA branch, which will be merged into main ASAP
